//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anand_Classes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Anand_ClassesEntities : DbContext
    {
        public Anand_ClassesEntities()
            : base("name=Anand_ClassesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table_Contact> Table_Contact { get; set; }
        public DbSet<Table_Feedback> Table_Feedback { get; set; }
        public DbSet<Table_Gallery> Table_Gallery { get; set; }
        public DbSet<Table_Material> Table_Material { get; set; }
        public DbSet<Table_Registration> Table_Registration { get; set; }
        public DbSet<Table_Teacher_Login> Table_Teacher_Login { get; set; }
    }
}
