//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anand_Classes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Registration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string S_Email { get; set; }
        public string S_Password { get; set; }
        public string DOB { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Education { get; set; }
        public string Profile { get; set; }
        public string Registration_Date { get; set; }
    }
}
